Generate logger local in RestResource
vlingo/xoom-turbo pull request #5
Opened 2020-10-22 17:25 UTC by Florian-Schoenherr

2020-10-23 01:38 UTC, VaughnVernon requested changes
@Florian-Schoenherr Nice work. Please remove the unnecessary import of `ResourceHandler` and both `extends ResourceHandler ` uses in class declarations.

2020-10-23 01:38 UTC, VaughnVernon commented on src/main/resources/codegen/RestResource.ftl
>  import io.vlingo.http.resource.ResourceHandler;
Remove.

2020-10-23 01:38 UTC, VaughnVernon commented on src/main/resources/codegen/RestResource.ftl
>  </#if>
Remove `extends ResourceHandler ` from both if and else declarations.

2020-10-23 01:41 UTC, VaughnVernon commented
@Florian-Schoenherr You should be able to test by running:

`$ mvn clean test`
or
`$ mvn clean install`

2020-10-23 10:35 UTC, Florian-Schoenherr commented
Tests should work again, thanks to @danilo-ambrosio!

I tried removing `extends ResourceHandler` on schemata as a test, which then gives back 404 on every API request. ServerActor also doesn't log routes from Resources without `extends ResourceHandler`.

2020-10-23 19:27 UTC, VaughnVernon requested changes
@Florian-Schoenherr Why is MySQL being used and replacing Postgres? If you prefer to use MySQL locally for your own testing, that's fine. But I am not sure why that would be replaced for everyone. Postgres is sort of our "standard" relational database.

If you and Danilo have agreed to this for some reason let me know. Otherwise I'd like for these Postgres to MySQL changes removed.

2020-10-23 19:29 UTC, VaughnVernon commented
@Florian-Schoenherr @danilo-ambrosio Sorry, I was unaware of any agreement to switch from Postgres to MySQL. I am fine with it if it is needed for some specific reason. Just let me know and I can merge all this.

2020-10-23 19:32 UTC, VaughnVernon requested changes
@Florian-Schoenherr I am not necessarily requesting a change. I just need to know if these are safe casts, always guaranteed to be non-null boolean.

2020-10-23 19:32 UTC, VaughnVernon commented on src/main/java/io/vlingo/xoom/codegen/template/TemplateStandard.java
> +            if((boolean) parameters.find(REQUIRE_ENTITY_LOADING)) {
What happens if the property is missing? Will there be a runtime NPE or CCE?

2020-10-23 19:32 UTC, VaughnVernon commented on src/main/java/io/vlingo/xoom/codegen/template/TemplateStandard.java
> +    BOOTSTRAP(parameters -> (boolean) parameters.find(USE_ANNOTATIONS) ?
What happens if the property is missing? Will there be a runtime NPE or CCE?

2020-10-24 07:16 UTC, Florian-Schoenherr commented
[MySQL was introduced here](https://github.com/vlingo/vlingo-xoom/commit/479d550cd3473dd015f347fae088765a91ad2adb) by @danilo-ambrosio. I think it's meant for testing, but it is also not replacing postgres right there, but hsqldb. Danilo only told me MySQL will be part of integration testing just for a while.

Casting was maybe not fine, changed it.

2020-10-24 13:30 UTC, merged